server:
  port: 8082

spring:
  application.name: pay-service

  datasource:
    url: jdbc:postgresql://localhost:5433/pay
    username: pay
    password: paypw
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: update
    properties.hibernate:
      format_sql: true
      jdbc.time_zone: UTC

  kafka:
    bootstrap-servers: localhost:29092

    consumer:
      group-id: pay-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # room 과 동일하게 JsonDeserializer 사용
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        isolation.level: read_committed
      auto-offset-reset: earliest

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # room 과 동일하게 JsonSerializer 사용
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true

app:
  topics:
    bookingRequested: booking.requested      # BookingProducer 가 쓰는 토픽
    holdApproved:    booking.hold-approved   # HoldConsumers 가 듣는 토픽
    holdDenied:      booking.hold-denied
    paymentRequested:  payment.requested
    paymentAuthorized: payment.authorized
    paymentFailed:     payment.failed

  kafka:
    groups:
      pay-hold: rr-pay-hold
      pay-payment: rr-pay-payment
  payment:
    return-url-base: "http://localhost:5173/payment/result"

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.rr.pay: DEBUG
    com.rr.room: DEBUG
    # Kafka 쪽
    org.springframework.kafka: INFO