server:
  port: 8082

spring:
  application.name: pay-service

  datasource:
    url: jdbc:postgresql://localhost:5433/pay
    username: pay
    password: paypw
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: update
    properties.hibernate:
      format_sql: true
      jdbc.time_zone: UTC

  kafka:
    bootstrap-servers: localhost:29092

    consumer:
      group-id: pay-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # room 과 동일하게 JsonDeserializer 사용
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        isolation.level: read_committed
      auto-offset-reset: earliest

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # room 과 동일하게 JsonSerializer 사용
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true

app:
  topics:
    # booking 에서 사용할 토픽 (BookingProducer @Value("\${app.topics.bookingRequested}"))
    bookingRequested: rr.booking.requested

    # 결제 단계 쪽에서 사용할 토픽들(나중에 payment 이벤트 쓸 때)
    paymentRequested:  payment.requested
    paymentAuthorized: payment.authorized
    paymentFailed:     payment.failed

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE