server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/room_reservation
    username: room
    password: roompw
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: room-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
        isolation.level: read_committed
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        enable.idempotence: true

app:
  topics:
    holdRequested: reservation.hold.requested
    holdApproved:  reservation.hold.approved
    holdDenied:    reservation.hold.denied
    confirmed:     reservation.confirmed
    cancelled:     reservation.cancelled
    paymentRequested:  payment.requested
    paymentAuthorized: payment.authorized
    paymentFailed:     payment.failed
  hold:
    ttlMinutes: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info
