server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  application.name: room-service

  datasource:
    url: jdbc:postgresql://localhost:5432/room_reservation
    username: room
    password: roompw
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: update
    properties.hibernate:
      format_sql: true
      jdbc.time_zone: UTC

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: room-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  topics:
    roomCreated: rr.room.created
    roomStatusUpdated: rr.room.status-updated

logging:
  level:
    org.springframework: INFO