server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always

spring:
  application.name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5434/user
    username: user
    password: userpw
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: update
    properties.hibernate:
      format_sql: true
      jdbc.time_zone: UTC

app:
  topics:
    roomCreated: rr.room.created
    roomStatusUpdated: rr.room.status-updated

    bookingRequested: booking.requested
    holdApproved: booking.hold-approved
    holdDenied: booking.hold-denied

    paymentRequested: payment.requested
    paymentAuthorized: payment.authorized
    paymentFailed: payment.failed

  kafka:
    groups:
      room-booking: rr-room-booking

logging:
  level:
    org.springframework: INFO